// This file was originally generated by ./chibi-scheme-emscripten ./tools/chibi-ffi lib/robj/gameengine.stub
// But for adding all the logic required by the engine, I'm manually adding code here
// This file eventually is put in the huge clibs.c file where all the modules are concatenated
// You can see what will be put in the clibs.c file executing
// $ find lib/ -name "gameengine.sld" | ./chibi-scheme-emscripten -q ./tools/chibi-genstatic

#include <chibi/eval.h>

#include <emscripten.h>
/*
types: ()
enums: ()
*/

void hello_world() {
  printf("SDL, Here we go!\n");
}

sexp sexp_say_hello_stub (sexp ctx, sexp self, sexp_sint_t n, sexp arg0) {
  if (! sexp_stringp(arg0))
    return sexp_type_exception(ctx, self, SEXP_STRING, arg0);
  printf("Hello %s\n", sexp_string_data(arg0));
  hello_world();
  return SEXP_VOID;
}


sexp sexp_init_library (sexp ctx, sexp self, sexp_sint_t n, sexp env, const char* version, const sexp_abi_identifier_t abi) {
  sexp_gc_var3(name, tmp, op);
  if (!(sexp_version_compatible(ctx, version, sexp_version)
        && sexp_abi_compatible(ctx, abi, SEXP_ABI_IDENTIFIER)))
    return SEXP_ABI_ERROR;
  sexp_gc_preserve3(ctx, name, tmp, op);
  op = sexp_define_foreign(ctx, env, "say-hello", 1, sexp_say_hello_stub);
  if (sexp_opcodep(op)) {
    sexp_opcode_return_type(op) = SEXP_VOID;
    sexp_opcode_arg1_type(op) = sexp_make_fixnum(SEXP_STRING);
  }
  sexp_gc_release3(ctx);
  return SEXP_VOID;
}

